// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHGBL4MrzlLmzaCznVBONe-RsqSmkdzG8',
    appId: '1:1058179878729:web:0832ba2203c2b4191c1498',
    messagingSenderId: '1058179878729',
    projectId: 'sba7o-73e16',
    authDomain: 'sba7o-73e16.firebaseapp.com',
    storageBucket: 'sba7o-73e16.appspot.com',
    measurementId: 'G-66DZ4L494R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC96oJwx9DDiE5gMwbGROFf1VQW62NnV6U',
    appId: '1:1058179878729:android:51a26e9f2cb44e091c1498',
    messagingSenderId: '1058179878729',
    projectId: 'sba7o-73e16',
    storageBucket: 'sba7o-73e16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3C5KCjw4dg14uWpPvJ5rgvUVOaqmB7RU',
    appId: '1:1058179878729:ios:84a4cda15be7646d1c1498',
    messagingSenderId: '1058179878729',
    projectId: 'sba7o-73e16',
    storageBucket: 'sba7o-73e16.appspot.com',
    iosBundleId: 'com.example.sba7oo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3C5KCjw4dg14uWpPvJ5rgvUVOaqmB7RU',
    appId: '1:1058179878729:ios:a8aaebbc951c328e1c1498',
    messagingSenderId: '1058179878729',
    projectId: 'sba7o-73e16',
    storageBucket: 'sba7o-73e16.appspot.com',
    iosBundleId: 'com.example.sba7oo.RunnerTests',
  );
}
